mlrun/test-notebooks

- test-dask-lightgbm/test-dask-lightgbm.ipynb
- test-dask-s3/test-dask-s3.ipynb
Resolved these two: 
* https://jira.iguazeng.com/browse/ML-3083
* https://jira.iguazeng.com/browse/ML-3084
> [Dask] Resolved issues when running from CI

- test-dask-lightgbm/test-dask-lightgbm.ipynb
- test-dask-s3/test-dask-s3.ipynb
* Decrease the size of data generated (OOM) - [ML-3111](https://jira.iguazeng.com/browse/ML-3111)
* Removed time assertion (machine is too weak) - [ML-3109](https://jira.iguazeng.com/browse/ML-3109)
> [Dask] Resolve issues for time assertion and oom

- test-horovod-pytorch/.test
- test-horovod-pytorch/test-horovod-pytorch.ipynb
- test-horovod-tensorflow/.test
- test-horovod-tensorflow/test-horovod-tensorflow.ipynb
- test-openmpi-s3/.test
- test-openmpi-s3/test-openmpi-s3.ipynb
Add the following tests:
* Open MPI using S3 
* Horovod with TensorFlow
* Horovod with PyTorch
Currently all is bugging out due to [ML-3119](https://jira.iguazeng.com/browse/ML-3119) but once this bug is fixed the tests should run.
> [OpenMPI + Horovod] Add multiple tests (3 notebooks)

- schedule/test-schedule.ipynb
Testing schedules flow and ensuring that the access key is hidden with reference.
Also checking that overwriting schedules is working.
> [Schedule] Adding test schedule notebook

- project_transfer/01_cross_project.ipynb
old xgboost version caused issues loading/exporting the model.
upgrading version
> [project-transfer] updating xgboost version

- test-horovod-pytorch/test-horovod-pytorch.ipynb
- test-horovod-tensorflow/test-horovod-tensorflow.ipynb
Reduced the epochs number to make the test easier on the machine.
> [Horovod] Shorten the training time

- project_transfer/01_cross_project.ipynb
> [project-transfer] update package

- test-horovod-pytorch/test-horovod-pytorch.ipynb
Changed relative paths to absolute paths
> [Horovod-PyTorch] Change relative paths to absolute paths

- test-dask-lightgbm/test-dask-lightgbm.ipynb
- test-dask-s3/test-dask-s3.ipynb
- test-horovod-pytorch/test-horovod-pytorch.ipynb
- test-horovod-tensorflow/test-horovod-tensorflow.ipynb
- test-openmpi-s3/test-openmpi-s3.ipynb
Change the deletion strategy so projects will be deleted regardless of existing runs.
> [Dask + OpenMPI] Change the deletion strategy

- test-handler-decorator/test-handler-decorator.ipynb
Add `pip install scikit-learn` to match local image version to code.
> [Handler Decorator] Add `scikit-learn` install

- serving_with_remote_func/00-prepare.ipynb
https://jira.iguazeng.com/browse/ML-3243
> install req for serving_with_remote_func : `lightgbm` and `plotly`

- test-dask-s3/test-dask-s3.ipynb
ticket: [ML-3297](https://jira.iguazeng.com/browse/ML-3297)
> [test-dask-s3] Add `tqdm` install

- test-dask-xgboost/.test
- test-dask-xgboost/test-dask-xgboost.ipynb
This test generates a big binarry classification data for later train a model on the generated data using XGBoost with and without Dask. Later it will verify that:
* The accuracy was not damaged in Dask.
* The dask run was faster (only possible on big data).
> [test-dask-xgboost] Testing XGBoost over Dask with MLRun

- test-dask-s3/test-dask-s3.ipynb
Ticket: [ML-3269](https://jira.iguazeng.com/browse/ML-3269) & [ML-3324](https://jira.iguazeng.com/browse/ML-3324)
> [test_dask_s3] Add `ipywidgets` install and update `with_limits` method

- test-dask-lightgbm/test-dask-lightgbm.ipynb
Update `with_limits` method to `with_eorker_limits`.
> [test-dask-lightgbm] Update `with_limits` method

- test-openmpi-s3/test-openmpi-s3.ipynb
Added missing installs for `ipywidgets` and `tqdm`.
> [test-openmpi-s3] Add pip installs

- test-handler-decorator/functions.py
- test-handler-decorator/test-handler-decorator.ipynb
Updated test to match 1.3.0 - or at lest the next rc (1.3.0-rc23)
> [test-handler-decorator] Updated test to match 1.3.0

- project_transfer/01_cross_project.ipynb
removed all underscores from function names
pipeline artifacts '_' separator has changed.
> [project-transfer] functions + artifact name update

- project_transfer/01_cross_project.ipynb
- remote_artifact_runtimes/01_mlrun_job.ipynb
- remote_artifact_runtimes/02_serving_and_pipeline.ipynb
- remote_artifact_runtimes/03_spark.ipynb
- spark_fs_remote/01_spark_fs_remote.ipynb
due to new convention in artifact name (project name and artifact name is concatenated with "-" and not "_") update was needed in all of these notebooks
> update artifact names

- test_packager/test_packager_example.ipynb
Added a test notebook for packagers
> Add test packager notebook

- test_packager/.test
- test_packager/test_packager_notebook.ipynb
contain fixed according Guy review
> [Test] Add packager notebook

- test_packager/test_packager_notebook.ipynb
Updated notebook to MLRun's https://github.com/mlrun/mlrun/pull/4625 changes.
> [test_packager] Update notebook to match `mlrun.package` updates

- test-git-commands/git-flow-check.ipynb
Part of the Usability coverage task force
> Tests of various mlrun commands used during git flow

- test_change_logger_format_jobs/test_logger_format_change_jobs.ipynb
related to - https://iguazio.atlassian.net/browse/ML-5763
> [TEST] Add test for changing logger format using env for mlrun jobs

- model_endpoints_tags_labels/test-ml-6609.ipynb
https://iguazio.atlassian.net/browse/ML-6609
> [Test] add notebook for ml-6609

- model_endpoints_tags_labels/test-ml-6609.ipynb
changed this line `db.list_model_endpoints(project=project.name,model=f"model:v{i}")` to get the model endpoint by it model name and tag instead of get the endpoint by it's index in the list - `db.list_model_endpoints(project=project.name)[0]` 
the issue was that the order of the return endpoints was changed between the versions
> [FIX] fix ml-6609 notebook

- model_endpoints_tags_labels/test-ml-6609.ipynb
related to https://iguazio.atlassian.net/browse/ML-8689
> [Model Monitoring] fix listing endpoints

- serving_remote_step/project.yaml
- serving_remote_step/remotestep.py
- serving_remote_step/serving-func.py
- serving_remote_step/test_serving_remote_function.ipynb
this notebook test this requirement fix - https://iguazio.atlassian.net/browse/ML-6373.
> Add test notebook for custom headers as part of the remote step

- test-horovod-tensorflow/test-horovod-tensorflow.ipynb
otherwise it will fail on CE with "tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at summary_kernels.cc:65 : UNIMPLEMENTED: File system scheme 's3' not implemented "
> test-horovod-tensorflow.ipynb: use local output_path
